services:
  db:
    image: postgres:18
    hostname: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes: 
      - postgres_data:/var/lib/postgresql

  minio:
    image: minio/minio
    container_name: minio
    hostname: photodump-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"


  app-api:
    build:
      context: .
      dockerfile: server/App.Api/Dockerfile 
    depends_on:
      - db
      - minio
    environment:
      AppDatabase__DatabaseProvider: "postgres"
      AppDatabase__ConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      ContentStore__ContentStoreProvider: "s3"
      ContentStore__AccessKey: "${MINIO_USER}"
      ContentStore__SecretKey: "${MINIO_PASSWORD}"
      ContentStore__Endpoint: "${MINIO_ENDPOINT}"
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
  minio_data: