services:
  db:
    image: postgres:18
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes: 
      - postgres_data:/var/lib/postgresql

  garage:
    image: dxflrs/garage:v2.1.0
    volumes:
      - ./storage/garage.toml:/etc/garage.toml
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data
    restart: always

  broker:
    image: rabbitmq:4.2.3-alpine
    ports:
      - "5672:5672"
    volumes:
      - broker_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${BROKER_USER}
      RABBITMQ_DEFAULT_PASS: ${BROKER_PASSWORD}
    restart: always

  proxy:
    image: nginx
    volumes:
      - ./infrastructure/proxy/nginx:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      PROXY_PORT: ${PROXY_PORT}
      APP_API_DOMAIN: ${APP_API_DOMAIN}
      APP_API_PORT: ${APP_API_PORT}
      CONTENT_STORE_DOMAIN: ${CONTENT_STORE_DOMAIN}
      GARAGE_API_PORT: ${GARAGE_API_PORT}
    depends_on:
      - app-api
      - garage
    restart: always

  app-api:
    build:
      context: .
      dockerfile: server/App.Api/Dockerfile 
    depends_on:
      - db
      - garage
      - broker
    environment:
      AppDatabase__DatabaseProvider: "postgres"
      AppDatabase__ConnectionString: "Host=db;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      ContentStore__ContentStoreProvider: "s3"
      ContentStore__AccessKey: "${GARAGE_APP_KEY}"
      ContentStore__SecretKey: "${GARAGE_APP_SECRET}"
      ContentStore__ExternalEndpoint: "${CONTENT_STORE_DOMAIN}"
      ContentStore__InternalEndpoint: garage:${GARAGE_API_PORT}
      ContentStore__Region: "${GARAGE_REGION}"
      SessionAuth__SessionDurationMinutes: 240 
      BrokerClient__Host: "broker"
      BrokerClient__Port: ${BROKER_PORT}
      BrokerClient__UserName: "${BROKER_USER}"
      BrokerClient__Password: "${BROKER_PASSWORD}"
      BrokerClient__QueueName: "photo-thumbnail"
      DOTNET_ENVIRONMENT: "Development"
    restart: always

volumes:
  postgres_data:
  garage_meta:
  garage_data:
  broker_data: