services:
  db:
    image: postgres:18
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes: 
      - postgres_data:/var/lib/postgresql

  garage:
    image: dxflrs/garage:v2.1.0
    env_file:
      - .env
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    volumes:
      - ./storage/garage.toml:/etc/garage.toml
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data

  app-api:
    build:
      context: .
      dockerfile: server/App.Api/Dockerfile 
    depends_on:
      - db
      - garage 
    environment:
      AppDatabase__DatabaseProvider: "postgres"
      AppDatabase__ConnectionString: "Host=db;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      ContentStore__ContentStoreProvider: "s3"
      ContentStore__AccessKey: "${GARAGE_APP_KEY}"
      ContentStore__SecretKey: "${GARAGE_APP_SECRET}"
      ContentStore__Endpoint: "garage:3900"
      ContentStore__Region: "${GARAGE_REGION}"
      SessionAuth__SessionDurationMinutes: 240 
      DOTNET_ENVIRONMENT: "Development"
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
  minio_data:
  garage_meta:
  garage_data: